# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghkit < Formula
  desc "CLI tool for installing GitHub project templates"
  homepage "https://github.com/optiflowic/ghkit"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/optiflowic/ghkit/releases/download/v1.0.0/ghkit_Darwin_x86_64.tar.gz"
      sha256 "03a8f1cadf780796fe00c5a0cf771021ba82f8be723bc143ef1b78f8730ff90e"

      def install
        bin.install "ghkit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/optiflowic/ghkit/releases/download/v1.0.0/ghkit_Darwin_arm64.tar.gz"
      sha256 "6cab6af318f01922def85b07e1acca0acb808e5711b2f630ca53093d5397ad88"

      def install
        bin.install "ghkit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/optiflowic/ghkit/releases/download/v1.0.0/ghkit_Linux_x86_64.tar.gz"
      sha256 "bd58465121621370d63b66fbad204f2ebc60fe21bab7a8a13b5d932fe4319d3a"
      def install
        bin.install "ghkit"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/optiflowic/ghkit/releases/download/v1.0.0/ghkit_Linux_arm64.tar.gz"
      sha256 "c87fcb6771dd206d3c5ddffd35bd450e896ed5caae86ef832b1df278a19ed243"
      def install
        bin.install "ghkit"
      end
    end
  end
end
