# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghkit" do
  desc "CLI tool for installing GitHub project templates"
  homepage "https://github.com/optiflowic/ghkit"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghkit"

  on_macos do
    on_intel do
      url "https://github.com/optiflowic/ghkit/releases/download/v1.0.0/ghkit_Darwin_x86_64.tar.gz"
      sha256 "27d3035e067e6a04505104d8c4dd5b389b35b9ec2913dbeed732cb1c810630ad"
    end
    on_arm do
      url "https://github.com/optiflowic/ghkit/releases/download/v1.0.0/ghkit_Darwin_arm64.tar.gz"
      sha256 "3c8177f90c2f97ae4836eba02819d0bce503c0f13019213eefd6f3a5e6698c52"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/optiflowic/ghkit/releases/download/v1.0.0/ghkit_Linux_x86_64.tar.gz"
      sha256 "ceb9dc74e2d96d2f22b4c7c70a41adbdf355390c75c966eb58a0751ca9871f13"
    end
    on_arm do
      url "https://github.com/optiflowic/ghkit/releases/download/v1.0.0/ghkit_Linux_arm64.tar.gz"
      sha256 "1cfed348231f1abd102b14a2546f70c15b3f38536a9618ccd10f58361dd0911b"
    end
  end

  # No zap stanza required
end
